### ISSUE TITLE
Is this repo still active??

### ISSUE THREAD

**Issue by wildaces215** [amzn/halo-third-party-sdk-for-node-js#5]
Is this repo still active? The last commit was  last year and wanted to know if it still is? Thanks in advance!

**Comment by jnathay** [comment]
Hello, yes this repo is still active.

**Comment by jnathay** [comment]
Yes this repo is still active. Thanks!

**Comment by wildaces215** [comment]
Hi there thank you for answering my question! I am currently an Amazon Halo user who might want to integrate the halo itself into my own custom app. When I look around on the internet I see other developers asking if there is an SDK and whatnot. I think if you let developers know more about this SDK then more people might use Halo itself! So I'll ask how do I get started with using the SDK for Amazon Halo?

**Comment by jnathay** [comment]
While the SDK is public, our API which enables data sharing is private and only open to select Amazon Halo partners. If you can share more about your use case and app, we can discuss internally your integration request. We'll update our documentation in the future if our closed API status changes.
